from fastapi import APIRouter
from models.response import ok, err
import fastf1
import pandas as pd
import time

router = APIRouter()

# 内存缓存
_cache: dict = {}

def _cache_get(key: str, ttl: int):
    entry = _cache.get(key)
    if entry and time.time() - entry["ts"] < ttl:
        return entry["data"]
    return None

def _cache_set(key: str, data):
    _cache[key] = {"ts": time.time(), "data": data}

@router.get("")
def get_events(year: int = 2026):
    cache_key = f"events:{year}"
    cached = _cache_get(cache_key, 6 * 3600)
    if cached:
        return ok(cached)
    try:
        schedule = fastf1.get_event_schedule(year)
        events = []
        for _, row in schedule.iterrows():
            race_time_utc = None
            s5 = row.get("Session5Date", None)
            if s5 is not None and not pd.isna(s5):
                try:
                    ts = pd.Timestamp(s5)
                    ts = ts.tz_convert("UTC") if ts.tzinfo else ts.tz_localize("UTC")
                    race_time_utc = ts.isoformat()
                except Exception:
                    pass

            events.append({
                "round":          int(row.get("RoundNumber", 0)),
                "name":           row.get("EventName", ""),
                "country":        row.get("Country", ""),
                "location":       row.get("Location", ""),
                "date":           str(row.get("EventDate", ""))[:10],
                "format":         row.get("EventFormat", ""),
                "race_time_utc":  race_time_utc,
            })
        _cache_set(cache_key, events)
        return ok(events)
    except Exception as e:
        return err(str(e))


# ── 赛道静态信息 ──────────────────────────────────────────────────────
# key = FastF1 Location 字段值
CIRCUIT_INFO = {
    "Melbourne": {
        "name_cn": "阿尔伯特公园赛道",
        "country": "澳大利亚",
        "city": "墨尔本",
        "length_km": 5.278,
        "laps": 58,
        "lap_record": "1:20.235",
        "lap_record_holder": "Charles Leclerc",
        "lap_record_year": 2022,
        "first_gp": 1996,
        "turns": 16,
        "drs_zones": 4,
        "type": "街道改建赛道",
        "direction": "顺时针",
        "characteristics": ["高速直道", "慢速弯角", "街道赛道感"],
        "highlights": ["赛季揭幕战，历史悠久", "湖边公园改建，风景优美", "2022年大改造后圈速大幅提升", "DRS区域多，超车机会丰富"],
        "tyre_strategy": "通常一停策略，软胎磨损较快",
        "weather": "3月澳洲秋季，气温适宜，偶有阵雨",
    },
    "Shanghai": {
        "name_cn": "上海国际赛车场",
        "country": "中国",
        "city": "上海",
        "length_km": 5.451,
        "laps": 56,
        "lap_record": "1:32.238",
        "lap_record_holder": "Michael Schumacher",
        "lap_record_year": 2004,
        "first_gp": 2004,
        "turns": 16,
        "drs_zones": 2,
        "type": "永久赛道",
        "direction": "顺时针",
        "characteristics": ["超长发卡弯", "高速S弯", "长直道"],
        "highlights": ["标志性发卡弯（T6-T7）考验刹车", "T1-T2高速S弯对下压力要求极高", "长主直道超车机会多", "2024年回归后人气高涨"],
        "tyre_strategy": "两停策略常见，轮胎磨损中等",
        "weather": "3月上海春季，气温偏低，可能有雨",
    },
    "Suzuka": {
        "name_cn": "铃鹿赛道",
        "country": "日本",
        "city": "铃鹿",
        "length_km": 5.807,
        "laps": 53,
        "lap_record": "1:30.983",
        "lap_record_holder": "Lewis Hamilton",
        "lap_record_year": 2019,
        "first_gp": 1987,
        "turns": 18,
        "drs_zones": 1,
        "type": "永久赛道",
        "direction": "顺时针（8字形）",
        "characteristics": ["8字形布局", "高速S弯群", "发卡弯"],
        "highlights": ["全球公认最具技术挑战性赛道之一", "S弯群（T1-T9）对车手技术要求极高", "Spoon弯+130R高速弯考验勇气", "日本车迷热情，氛围极佳"],
        "tyre_strategy": "通常一停，轮胎磨损相对温和",
        "weather": "3-4月日本春季，气温凉爽，偶有雨",
    },
    "Miami Gardens": {
        "name_cn": "迈阿密国际赛道",
        "country": "美国",
        "city": "迈阿密花园",
        "length_km": 5.412,
        "laps": 57,
        "lap_record": "1:29.708",
        "lap_record_holder": "Max Verstappen",
        "lap_record_year": 2023,
        "first_gp": 2022,
        "turns": 19,
        "drs_zones": 3,
        "type": "街道改建赛道",
        "direction": "顺时针",
        "characteristics": ["高速弯角", "慢速技术区", "长直道"],
        "highlights": ["NFL球场Hard Rock Stadium周边改建", "人工海湾景观独特", "2022年新加入赛历，迅速成为热门站", "DRS区域多，超车精彩"],
        "tyre_strategy": "一停或两停均可，策略多样",
        "weather": "5月迈阿密，炎热潮湿，气温30°C+",
    },
    "Monte Carlo": {
        "name_cn": "摩纳哥街道赛道",
        "country": "摩纳哥",
        "city": "蒙特卡洛",
        "length_km": 3.337,
        "laps": 78,
        "lap_record": "1:12.909",
        "lap_record_holder": "Lewis Hamilton",
        "lap_record_year": 2021,
        "first_gp": 1950,
        "turns": 19,
        "drs_zones": 1,
        "type": "街道赛道",
        "direction": "顺时针",
        "characteristics": ["极窄街道", "无法超车", "隧道高速段"],
        "highlights": ["F1最古老最负盛名的赛道", "赛道极窄，超车几乎不可能", "排位赛决定一切", "隧道段时速超过280km/h", "游艇赌场，F1最奢华赛事"],
        "tyre_strategy": "排位赛策略为主，正赛超车极难",
        "weather": "5月地中海气候，温暖宜人",
    },
    "Barcelona": {
        "name_cn": "加泰罗尼亚赛道",
        "country": "西班牙",
        "city": "巴塞罗那",
        "length_km": 4.657,
        "laps": 66,
        "lap_record": "1:16.330",
        "lap_record_holder": "Max Verstappen",
        "lap_record_year": 2023,
        "first_gp": 1991,
        "turns": 14,
        "drs_zones": 2,
        "type": "永久赛道",
        "direction": "顺时针",
        "characteristics": ["高速弯角", "技术性慢弯", "轮胎考验"],
        "highlights": ["F1测试赛道，各队对此了如指掌", "T3高速弯对下压力要求极高", "轮胎磨损严重，策略至关重要", "超车困难，排位赛重要"],
        "tyre_strategy": "两停策略常见，轮胎磨损严重",
        "weather": "6月西班牙夏季，炎热干燥",
    },
    "Spielberg": {
        "name_cn": "红牛赛道",
        "country": "奥地利",
        "city": "施皮尔贝格",
        "length_km": 4.318,
        "laps": 71,
        "lap_record": "1:05.619",
        "lap_record_holder": "Carlos Sainz",
        "lap_record_year": 2020,
        "first_gp": 1970,
        "turns": 10,
        "drs_zones": 3,
        "type": "永久赛道",
        "direction": "顺时针",
        "characteristics": ["短圈高海拔", "大量上坡下坡", "超车机会多"],
        "highlights": ["F1最短赛道之一，仅10个弯角", "高海拔影响发动机冷却", "DRS区域多，超车精彩", "阿尔卑斯山脚下，风景壮观"],
        "tyre_strategy": "一停策略为主，圈数少磨损轻",
        "weather": "7月奥地利夏季，午后常有雷阵雨",
    },
    "Silverstone": {
        "name_cn": "银石赛道",
        "country": "英国",
        "city": "银石",
        "length_km": 5.891,
        "laps": 52,
        "lap_record": "1:27.097",
        "lap_record_holder": "Max Verstappen",
        "lap_record_year": 2020,
        "first_gp": 1950,
        "turns": 18,
        "drs_zones": 2,
        "type": "永久赛道",
        "direction": "顺时针",
        "characteristics": ["高速弯角群", "Maggotts-Becketts连续弯", "长直道"],
        "highlights": ["F1历史上第一站大奖赛（1950年）", "Copse/Maggotts/Becketts高速弯群极具挑战", "英国车迷热情，汉密尔顿主场", "天气多变，雨战概率高"],
        "tyre_strategy": "两停策略常见，高速弯磨损大",
        "weather": "7月英国夏季，多云多雨",
    },
    "Budapest": {
        "name_cn": "匈牙利赛道",
        "country": "匈牙利",
        "city": "布达佩斯",
        "length_km": 4.381,
        "laps": 70,
        "lap_record": "1:16.627",
        "lap_record_holder": "Lewis Hamilton",
        "lap_record_year": 2020,
        "first_gp": 1986,
        "turns": 14,
        "drs_zones": 2,
        "type": "永久赛道",
        "direction": "顺时针",
        "characteristics": ["慢速技术赛道", "超车困难", "下压力需求高"],
        "highlights": ["东欧第一站F1大奖赛（1986年）", "赛道弯多直道少，超车极难", "被称为'匈牙利摩纳哥'", "轮胎磨损严重，策略复杂"],
        "tyre_strategy": "两停策略常见，轮胎磨损严重",
        "weather": "7-8月匈牙利夏季，炎热干燥",
    },
    "Spa-Francorchamps": {
        "name_cn": "斯帕-弗朗科尔尚赛道",
        "country": "比利时",
        "city": "斯帕",
        "length_km": 7.004,
        "laps": 44,
        "lap_record": "1:46.286",
        "lap_record_holder": "Valtteri Bottas",
        "lap_record_year": 2018,
        "first_gp": 1950,
        "turns": 19,
        "drs_zones": 2,
        "type": "永久赛道",
        "direction": "顺时针",
        "characteristics": ["F1最长赛道", "Eau Rouge/Raidillon高速弯", "天气极端多变"],
        "highlights": ["F1最长赛道，全程7km", "Eau Rouge/Raidillon是F1最著名弯角之一", "天气变化极快，同一圈可能晴雨交替", "Pouhon高速弯考验勇气"],
        "tyre_strategy": "一停策略为主，低速弯少磨损轻",
        "weather": "7-8月比利时夏季，天气极不稳定",
    },
    "Zandvoort": {
        "name_cn": "赞德福特赛道",
        "country": "荷兰",
        "city": "赞德福特",
        "length_km": 4.259,
        "laps": 72,
        "lap_record": "1:11.097",
        "lap_record_holder": "Lewis Hamilton",
        "lap_record_year": 2021,
        "first_gp": 1952,
        "turns": 14,
        "drs_zones": 2,
        "type": "永久赛道",
        "direction": "顺时针",
        "characteristics": ["高倾斜弯道", "沙丘地形", "超车困难"],
        "highlights": ["2021年回归赛历，维斯塔潘主场", "独特的高倾斜弯道（Hugenholtz/Arie Luyendyk）", "沙丘地形，赛道紧凑", "荷兰橙色军团氛围震撼"],
        "tyre_strategy": "两停策略常见，高倾斜弯磨损大",
        "weather": "8-9月荷兰夏末，凉爽多风",
    },
    "Monza": {
        "name_cn": "蒙扎赛道",
        "country": "意大利",
        "city": "蒙扎",
        "length_km": 5.793,
        "laps": 53,
        "lap_record": "1:21.046",
        "lap_record_holder": "Rubens Barrichello",
        "lap_record_year": 2004,
        "first_gp": 1950,
        "turns": 11,
        "drs_zones": 2,
        "type": "永久赛道",
        "direction": "顺时针",
        "characteristics": ["F1最高速赛道", "长直道", "低下压力设定"],
        "highlights": ["F1最高速赛道，平均时速超过260km/h", "意大利法拉利主场，Tifosi热情如火", "低下压力设定，直道超车精彩", "历史悠久，1950年首届F1即在此举办"],
        "tyre_strategy": "一停策略为主，低下压力磨损轻",
        "weather": "9月意大利初秋，温暖宜人",
    },
    "Madrid": {
        "name_cn": "马德里街道赛道",
        "country": "西班牙",
        "city": "马德里",
        "length_km": 5.47,
        "laps": 55,
        "lap_record": "—",
        "lap_record_holder": "—",
        "lap_record_year": 2026,
        "first_gp": 2026,
        "turns": 20,
        "drs_zones": 3,
        "type": "街道赛道",
        "direction": "顺时针",
        "characteristics": ["全新街道赛道", "IFEMA展览中心周边", "高速与慢速结合"],
        "highlights": ["2026年全新加入赛历", "马德里IFEMA展览中心周边改建", "西班牙第二站，与巴塞罗那同年举办", "赛道设计融合高速直道与技术弯角"],
        "tyre_strategy": "待定，首届赛事",
        "weather": "6月马德里夏季，炎热干燥，气温35°C+",
    },
    "Baku": {
        "name_cn": "巴库城市赛道",
        "country": "阿塞拜疆",
        "city": "巴库",
        "length_km": 6.003,
        "laps": 51,
        "lap_record": "1:43.009",
        "lap_record_holder": "Charles Leclerc",
        "lap_record_year": 2019,
        "first_gp": 2016,
        "turns": 20,
        "drs_zones": 2,
        "type": "街道赛道",
        "direction": "顺时针",
        "characteristics": ["超长主直道", "极窄城堡区", "高速街道"],
        "highlights": ["主直道长达2.2km，最高时速超过360km/h", "城堡区极窄，宽度仅7.6m", "安全车出动频繁，比赛充满变数", "里海海岸线风景壮观"],
        "tyre_strategy": "安全车影响大，策略多变",
        "weather": "4-6月阿塞拜疆春夏，温暖，偶有强风",
    },
    "Marina Bay": {
        "name_cn": "滨海湾街道赛道",
        "country": "新加坡",
        "city": "新加坡",
        "length_km": 4.94,
        "laps": 62,
        "lap_record": "1:35.867",
        "lap_record_holder": "Kevin Magnussen",
        "lap_record_year": 2018,
        "first_gp": 2008,
        "turns": 19,
        "drs_zones": 3,
        "type": "街道赛道",
        "direction": "逆时针",
        "characteristics": ["夜间赛事", "高温高湿", "慢速技术赛道"],
        "highlights": ["F1唯一夜间赛事，灯光璀璨", "高温高湿，体能消耗极大", "安全车出动频繁", "滨海湾金沙酒店为背景，景色绝美"],
        "tyre_strategy": "安全车影响大，策略多变",
        "weather": "9-10月新加坡，高温高湿，气温32°C+",
    },
    "Austin": {
        "name_cn": "美洲赛道",
        "country": "美国",
        "city": "奥斯汀",
        "length_km": 5.513,
        "laps": 56,
        "lap_record": "1:36.169",
        "lap_record_holder": "Charles Leclerc",
        "lap_record_year": 2019,
        "first_gp": 2012,
        "turns": 20,
        "drs_zones": 2,
        "type": "永久赛道",
        "direction": "逆时针",
        "characteristics": ["高速T1上坡弯", "技术性中段", "长直道"],
        "highlights": ["T1上坡盲弯是F1最精彩的超车点之一", "赛道设计融合多个经典赛道元素", "美国最受欢迎的F1赛事", "音乐节氛围，德州风情"],
        "tyre_strategy": "两停策略常见，轮胎磨损中等",
        "weather": "10月德州秋季，温暖，偶有雨",
    },
    "Mexico City": {
        "name_cn": "墨西哥城赛道",
        "country": "墨西哥",
        "city": "墨西哥城",
        "length_km": 4.304,
        "laps": 71,
        "lap_record": "1:17.774",
        "lap_record_holder": "Valtteri Bottas",
        "lap_record_year": 2021,
        "first_gp": 1963,
        "turns": 17,
        "drs_zones": 3,
        "type": "永久赛道",
        "direction": "顺时针",
        "characteristics": ["超高海拔", "低空气密度", "长直道"],
        "highlights": ["海拔2285m，F1最高海拔赛道", "稀薄空气导致发动机功率下降约25%", "DRS效果极强，超车精彩", "墨西哥车迷热情，佩雷斯主场"],
        "tyre_strategy": "一停策略为主，低空气密度磨损轻",
        "weather": "10-11月墨西哥秋季，温暖干燥",
    },
    "São Paulo": {
        "name_cn": "英特拉格斯赛道",
        "country": "巴西",
        "city": "圣保罗",
        "length_km": 4.309,
        "laps": 71,
        "lap_record": "1:10.540",
        "lap_record_holder": "Valtteri Bottas",
        "lap_record_year": 2018,
        "first_gp": 1973,
        "turns": 15,
        "drs_zones": 2,
        "type": "永久赛道",
        "direction": "逆时针",
        "characteristics": ["高海拔", "天气多变", "超车机会多"],
        "highlights": ["巴西大奖赛历史悠久，塞纳的主场", "天气变化极快，雨战概率高", "Senna S弯是F1最著名弯角之一", "逆时针赛道，对车手体能要求高"],
        "tyre_strategy": "策略多变，天气影响大",
        "weather": "11月巴西春季，高温多雨",
    },
    "Las Vegas": {
        "name_cn": "拉斯维加斯街道赛道",
        "country": "美国",
        "city": "拉斯维加斯",
        "length_km": 6.201,
        "laps": 50,
        "lap_record": "1:35.490",
        "lap_record_holder": "Oscar Piastri",
        "lap_record_year": 2023,
        "first_gp": 2023,
        "turns": 17,
        "drs_zones": 2,
        "type": "街道赛道",
        "direction": "顺时针",
        "characteristics": ["超长直道", "夜间赛事", "低温挑战"],
        "highlights": ["拉斯维加斯大道为主直道，灯红酒绿", "深夜举办，气温可低至10°C以下", "2023年回归，首届赛事充满戏剧性", "超长直道最高时速超过340km/h"],
        "tyre_strategy": "低温影响轮胎预热，策略复杂",
        "weather": "11月拉斯维加斯深夜，寒冷，气温5-15°C",
    },
    "Lusail": {
        "name_cn": "卢塞尔国际赛道",
        "country": "卡塔尔",
        "city": "卢塞尔",
        "length_km": 5.419,
        "laps": 57,
        "lap_record": "1:24.319",
        "lap_record_holder": "Max Verstappen",
        "lap_record_year": 2023,
        "first_gp": 2021,
        "turns": 16,
        "drs_zones": 2,
        "type": "永久赛道",
        "direction": "顺时针",
        "characteristics": ["高速流畅赛道", "夜间赛事", "轮胎磨损严重"],
        "highlights": ["高速流畅赛道，平均时速高", "夜间举办，气温相对凉爽", "轮胎磨损极为严重，两停甚至三停", "2021年首届赛事即精彩纷呈"],
        "tyre_strategy": "两停甚至三停，轮胎磨损极严重",
        "weather": "11-12月卡塔尔秋冬，夜间凉爽",
    },
    "Yas Marina": {
        "name_cn": "亚斯马里纳赛道",
        "country": "阿联酋",
        "city": "阿布扎比",
        "length_km": 5.281,
        "laps": 58,
        "lap_record": "1:26.103",
        "lap_record_holder": "Max Verstappen",
        "lap_record_year": 2021,
        "first_gp": 2009,
        "turns": 16,
        "drs_zones": 2,
        "type": "永久赛道",
        "direction": "逆时针",
        "characteristics": ["日落夜间赛事", "技术性赛道", "赛季收官站"],
        "highlights": ["赛季收官站，冠军常在此决出", "日落时分开赛，夜间结束，景色壮观", "2021年赛道大改造，超车机会增加", "亚斯岛豪华设施，F1最奢华赛事之一"],
        "tyre_strategy": "一停策略为主，轮胎磨损中等",
        "weather": "11-12月阿布扎比，温暖宜人，气温25°C",
    },
    "Montréal": {
        "name_cn": "吉尔·维伦纽夫赛道",
        "country": "加拿大",
        "city": "蒙特利尔",
        "length_km": 4.361,
        "laps": 70,
        "lap_record": "1:13.078",
        "lap_record_holder": "Valtteri Bottas",
        "lap_record_year": 2019,
        "first_gp": 1978,
        "turns": 14,
        "drs_zones": 2,
        "type": "半街道赛道",
        "direction": "顺时针",
        "characteristics": ["岛屿赛道", "冠军墙", "高速直道"],
        "highlights": ["圣母岛上改建，独特的岛屿赛道", "著名的'冠军墙'（T13-T14）", "安全车出动频繁，比赛充满变数", "加拿大车迷热情，维伦纽夫家族主场"],
        "tyre_strategy": "安全车影响大，策略多变",
        "weather": "6月加拿大夏季，温暖，偶有雨",
    },
}


@router.get("/{round_num}/circuit")
def get_circuit_info(round_num: int, year: int = 2026):
    cache_key = f"circuit:{year}:{round_num}"
    cached = _cache_get(cache_key, 6 * 3600)
    if cached:
        return ok(cached)
    try:
        schedule = fastf1.get_event_schedule(year)
        row = schedule[schedule["RoundNumber"] == round_num]
        if row.empty:
            return err(f"Round {round_num} not found")
        location = row.iloc[0].get("Location", "")
        country = row.iloc[0].get("Country", "")
        event_name = row.iloc[0].get("EventName", "")

        info = CIRCUIT_INFO.get(location)
        result = {
            "location": location,
            "country": country,
            "event_name": event_name,
            "detail": info,
        }
        _cache_set(cache_key, result)
        return ok(result)
    except Exception as e:
        return err(str(e))
